### ISSUE TITLE
Support running this right after creating a tag in a workflow

### ISSUE THREAD

**Issue by fregante** [fregante/release-with-changelog#1]
I'm opening this issue to keep track of this feature as discussed in https://github.com/fregante/github-url-detection/pull/30 and https://github.com/sindresorhus/refined-github/pull/3421

Currently this action only supports the `on.push.tag` event

**Comment by notlmn** [comment]
> Currently this action only supports the `on.push.tag` event

That's because we can be sure that we always have access to the tag for which we want to create a release for

https://github.com/notlmn/release-with-changelog/blob/a3b2ce4e86a700ecfd8f13ff9a928afc1fd4dd11/index.js#L13

---------------

Is there any way that we could do the same on other events, if yes then most of this "run only on specific condition" would be delegated back to user. no?

**Comment by fregante** [comment]
That's what I did in `daily-version-action`: it uses the pushed tag automatically, and if it's not found it fetches again and uses the latest tag.

**Comment by fregante** [comment]
For now you could use, in order:

1. an input (that you'd receive from [`daily-version-action`](https://github.com/fregante/daily-version-action/blob/f1e98ad8f95d12d77b94ffbd83cc0aa84861a1a3/index.js#L10))
2. `GITHUB_REF` if it's a tag
3. the latest tag

**Comment by notlmn** [comment]
I suppose this wouldn't be a breaking change and would function exactly as it previously was?

**Comment by notlmn** [comment]
>     1. an input (that you'd receive from `daily-version-action`

That requires configuring a new input here?

**Comment by fregante** [comment]
> I suppose this wouldn't be a breaking change and would function exactly as it previously was?

Yeah, the pushed tag is still at the top, so that's unchanged. However I think you should use a `token` input instead of the env as well. This is what GitHub uses: https://github.com/actions/checkout#checkout-multiple-repos-private

**Comment by notlmn** [comment]
> For now you could use, in order:
> 1. an input (that you'd receive from [`daily-version-action`](https://github.com/fregante/daily-version-action/blob/f1e98ad8f95d12d77b94ffbd83cc0aa84861a1a3/index.js#L10))
> 1. `GITHUB_REF` if it's a tag
> 1. the latest tag

Q: If latest tag is already available, why would we ask user for input? Any specific usercase?

**Comment by fregante** [comment]
- 2 would be easier to implement than 3, if you don't implement 3
- `workflow_dispatch` would let me specify each tag to create a release note for it

**Comment by notlmn** [comment]
@fregante, is https://github.com/notlmn/release-with-changelog/blob/run-anywhere/index.js what you are hoping for?

**Comment by fregante** [comment]
Kinda, but it should get the tags last, not first. No need to make run git at all if there’s an input or GITHUB_REF

**Comment by notlmn** [comment]
> but it should get the tags last, not first

They are [sorted](https://github.com/notlmn/release-with-changelog/blob/run-anywhere/index.js#L16) as latest first, so `tags[0]` is the latest tag.

---

> No need to make run git at all if there’s an input or GITHUB_REF

We use this list later to construct [range](https://github.com/notlmn/release-with-changelog/blob/run-anywhere/index.js#L34) to diff for.
