### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by fregante** [fregante/release-with-changelog#2]
I think the docs should include:

- [ ] What happens if a tag already has a release? Is it overridden?
- [ ] What events are supported? Currently only `on.push.tags`, apparently
- [ ] A full workflow is always welcome. Perhaps it should link to its own `release.yml` file

**Comment by notlmn** [comment]
The first couple issues are almost resolved by #3, but yes, we need more documentation.

Edit: Also needs updated screenshot as per #5.

**Comment by fregante** [comment]
> * [ ]  What happens if a tag already has a release? Is it overridden?

This happens:
```
Using pushed tag as reference: v1.2.0
Computed range: v1.1.1..v1.2.0
##[error]Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
```

> Edit: Also needs updated screenshot as per #5.

The visual output is basically unchanged

**Comment by notlmn** [comment]
> This happens:
> 
> ```
> Using pushed tag as reference: v1.2.0
> Computed range: v1.1.1..v1.2.0
> ##[error]Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
> ```

Because IMO failing with an error is easier than replacing existing releases, which could be a destructive action.

----------

> Edit: Also needs updated screenshot as per #5

`github-actions` is tagged as the author for releases going forward, not the owner of the repo (as we were using custom PAT under the label `secrets.RELEASE_TOKEN` before).

**Comment by fregante** [comment]
Ah I see what you mean. Yes that’s fine
