### ISSUE TITLE
Have a `exclude` preset

### ISSUE THREAD

**Issue by fregante** [fregante/release-with-changelog#20]
```yml
exclude: true
```

should mean

```ymlR
exclude: '^Meta|^Document|^Readme|readme$|^Lint|^Refactor|^Update.+dependencies$|^\d\.\d\.\d'
```

**Comment by notlmn** [comment]
I did work on this (now available at https://github.com/notlmn/release-with-changelog/tree/exclude-preset branch), but haven't got the time to test it and raise a PR. Please do test or I will manage to do that tonight.

**Comment by fregante** [comment]
It might be worth adding some tests first: https://github.com/notlmn/release-with-changelog/issues/21
