### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by fregante** [fregante/release-with-changelog#21]
In my latest action I extracted [the core function](https://github.com/fregante/title-to-labels-action/blob/main/parse-title.js) and [tested that](https://github.com/fregante/title-to-labels-action/blob/main/index.test.js) using the setup from the original [action template](https://github.com/actions/javascript-action).

For this action, perhaps you could extract and test the commit-to-notes part, which is the core feature:

```js
function generateReleaseNotes({commits, commitTemplate, releaseTemplate}) {
	const commitEntries = [];
	if (commits.length === 0) {
		commitEntries.push('_Maintenance release_');
	} else {
		for (const {hash, title} of commits) {
			const line = commitTemplate
				.replace('{hash}', hash)
				.replace('{title}', title)
				.replace('{url}', repoURL + '/commit/' + hash);
			commitEntries.push(line);
		}
	}
	return releaseTemplate
				.replace('{commits}', commitEntries.join('\n'))
				.replace('{range}', `[\`${range}\`](${repoURL}/compare/${range})`)
}
```

Testing the git part is harder and requires mocking, but this shouldn't be too difficult.

**Comment by notlmn** [comment]
This only tests the release notes part, given commits already filtered out, but that's a good start anyway.

**Comment by notlmn** [comment]
Opened #22 for you to review 😁
