### ISSUE TITLE
 Validation Failed

### ISSUE THREAD

**Issue by datapolitical** [fregante/release-with-changelog#25]
I’m getting an odd error: 
Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}

nothing I’ve googled seems directly applicable, I’m using the standard config in this file, and I created the package.json.

Any ideas what’s up?

https://github.com/datapolitical/chrisfnicholson.github.io/actions/runs/448268906

**Comment by notlmn** [comment]
I see that you are using v2 of this extension in the release file, we fixed a bunch of issues and released v3, use that instead.

Here's a complete release file for you to look at: https://github.com/notlmn/browser-extension-template/blob/master/.github/workflows/release.yml
