### ISSUE TITLE
Output a `release_upload_url` so other actions can attach files

### ISSUE THREAD

**Issue by fregante** [fregante/release-with-changelog#34]
https://github.com/actions/upload-release-asset can be used to attach files to releases, but it takes an "upload url" as parameter.

`release-with-changelog` should output this URL as well: https://docs.github.com/en/rest/reference/repos#upload-a-release-asset

Apparently it can be generated easily with just the release ID, which this action already has access to

**Comment by BelKed** [comment]
I think, it would be better add `file` parameter – like in https://github.com/marketplace/actions/upload-files-to-a-github-release
