### ISSUE TITLE
Always seems to be missing one commit.

### ISSUE THREAD

**Issue by fredbradley** [fregante/release-with-changelog#36]
Hello I’ve been testing this today however it seems that each time it misses the first commit of the group. 

Crude example can be found: https://github.com/fredbradley/actions-test/releases/tag/v0.3.1

but when you see the compare you see it’s three commits not two.

**Comment by fredbradley** [comment]
Can I have some help! 🙏

**Comment by fregante** [comment]
I'm not sure of what's happening, the tests work correctly:

- Real diff: https://github.com/fregante/release-with-changelog/compare/v3.0.0...v3.1.0
- https://github.com/fregante/release-with-changelog/blob/f047902b085bbb7ffae3ecd36d73842b76355dad/generate-release-notes.test.js#L11-L17

I wonder if the merge commit in your diff is throwing the count off somehow

**Comment by fredbradley** [comment]
Perhaps... I’ll try some more testing today perhaps with a few more than just two commits.

**Comment by fregante** [comment]
Something is definitely wrong. I just tried this command on this repo and it reports something unexpected:


```
❯ git log --format=%H¬%ad¬%s --date=short v3.1.0..v3.2.0
ef5326c2f6295cb5dc7b682c02832cb36c63409e¬2021-02-19¬Fix failing custom date format test
94ac12dd22dc363ac232ac8da1b79415e9a72faa¬2021-02-17¬Minor nits fix
171cd29b6480f2f5203073b5eca949bf87e38aa4¬2021-02-15¬Shorted dateFormat
fabe913b9573c3d66d71f2e06e7c16339697288b¬2021-02-15¬Improve dateFormat variable and add date test
ff7c0c0f44a3f20fccae845eb7c6bc3421c6df7c¬2021-02-15¬var –> const
695b2c127bb0b3ade1985f0a0b51901bce19eb7d¬2021-02-15¬Error fix
e504452f812061eb8232030cca45445f89b31389¬2021-02-15¬Improve code structure
a80b8794483d889f5b007a400100a819512f8b1c¬2021-02-15¬Fix bug, when longer or shorter date causing bad date, hash and title + revert formatting in `action.yml`
9512e689cebf30a861422b842454595b05cbf891¬2021-02-14¬Add `{date}` replacement  with options (#30)
6e89f5c9d6622f54ca284c06aa89fa7391cd86f7¬2021-02-04¬Update user in examples
5c804153ef8227047cf9bf373a704791aa3ee755¬2020-12-30¬Bump node-notifier from 8.0.0 to 8.0.1 (#26)
524027dd065f8486af7919212e355aa5523bebbd¬2020-12-30¬Bump ini from 1.3.5 to 1.3.8 (#24)
a170b2e671cf2763b5060b4e4747401181929635¬2020-10-23¬Fix minor typo in readme headings
```

This doesn't match GitHub’s diff, which only has 5 commits: https://github.com/fregante/release-with-changelog/compare/v3.1.0...v3.2.0

cc @notlmn

**Comment by BelKed** [comment]
When I clone this repository and run `git log`, it outputs just those commits:
```console
❯ git log --format=%H¬%ad¬%s --date=short v3.1.0..v3.2.0
f047902b085bbb7ffae3ecd36d73842b76355dad¬2021-02-22¬Add support for `{date}` replacement (#33)
6e89f5c9d6622f54ca284c06aa89fa7391cd86f7¬2021-02-04¬Update user in examples
5c804153ef8227047cf9bf373a704791aa3ee755¬2020-12-30¬Bump node-notifier from 8.0.0 to 8.0.1 (#26)
524027dd065f8486af7919212e355aa5523bebbd¬2020-12-30¬Bump ini from 1.3.5 to 1.3.8 (#24)
a170b2e671cf2763b5060b4e4747401181929635¬2020-10-23¬Fix minor typo in readme headings
```

**Comment by fredbradley** [comment]
I get the same output as @BelKed.

**Comment by BelKed** [comment]
Also, when I run `git log` on cloned [fredbradley/actions-test](https://github.com/fredbradley/actions-test), it outputs 3 instead 2 commits:
```console
❯ git log --format=%H¬%ad¬%s --date=short v0.3.0..v0.3.1
bb5441d8617c586d3a676e49b1113743210666a2¬2021-02-24¬chore(release): Automated version bumping to v0.3.1
4fcb30dcc5eab68717260ea49f216bd198e3337c¬2021-02-24¬Merge branch 'master' of github.com:fredbradley/actions-test
4cf6469146d04e314f59d516d73e8cded2e66150¬2021-02-24¬testing out something else
```

**Comment by fredbradley** [comment]
Is it to do with the additional use of `stefanzweifel/git-auto-commit-action@v4` in my action which always adds the `chore(release)` commit? 

I've just added a [v0.6.0](https://github.com/fredbradley/actions-test/releases/tag/v0.6.0) with many more commits, and no 'Merge' commit messages. But the changelog is still only show two commits.

**Comment by BelKed** [comment]
Try running just `fregante/release-with-changelog@v3` action, so we could say, that is caused by it...

**Comment by fredbradley** [comment]
In https://github.com/fredbradley/actions-test/releases/tag/v0.7.0 I've removed the other @stefanzweifel action, and now the changelog shows all commits as expected. 

So I guess I need to work out what it is with the other action that is suppressing it all. I've a feeling it's to do with the `tag` parameter.

**Comment by BelKed** [comment]
I think, that is caused by creating a commit in action. You maybe have to fetch second time before creating a release to get all commits using `actions/checkout@v2`...

**Comment by fregante** [comment]
Unfortunately the output of GitHub Actions matches mine. Check out the CI log of this failing commit: https://github.com/fregante/release-with-changelog/pull/38/commits/ff232905b73f054566686cd183d4928ffbbde891

**Comment by stefanzweifel** [comment]
I think this issue is related to one reported on the git-auto-commit Action repo: https://github.com/stefanzweifel/git-auto-commit-action/issues/145.

Due to a bug, the created commit and tag are not pushed together to the remote repository. A PR (https://github.com/stefanzweifel/git-auto-commit-action/pull/146) has been prepared to fix this issue.

**Comment by fregante** [comment]
This action does not create tags nor commits and the same applies to git locally and on GHA on old tags, so it’s not related.
