### ISSUE TITLE
Use native GitHub release generator

### ISSUE THREAD

**Issue by fregante** [fregante/release-with-changelog#53]
This would be a big change, but I think it makes sense (especially because it would save us from release notes generation bugs and further requests).

The v3 of this action and the underlying generator can be forked as they're released under MIT.

Such change would let us drop most of the current code and replace it with: https://github.com/MylesBorins/node-osc/blob/v6.1.11/.github/workflows/create-release.yml#L26-L41

The native generator can be configured separately from this action as well, so most options except `title`, `draft` and `prerelease` can be dropped as well.

It would close:

- https://github.com/fregante/release-with-changelog/issues/46
- https://github.com/fregante/release-with-changelog/issues/36
- https://github.com/fregante/release-with-changelog/issues/17

Context:

- https://github.com/refined-github/refined-github/issues/4008#issuecomment-996057501

**Comment by mdirshaddev** [comment]
@fregante ok. Thanks bro

**Comment by fregante** [comment]
It looks like this whole action can be replaced by a single `gh-cli` line:

- https://github.com/refined-github/refined-github/pull/6084

I'm contemplating turning the action into a "composite action", which accepts a couple of inputs (like assets) and then calls `gh-cli`

Or potentially just deprecate and archive the action, which is easier. The advantage of wrapping the CLI in an action is that it would allow slightly easier configuration, e.g.:

- automatically picking the latest tag
- automatically zipping any folders 

It may be worth it, but also I don’t think I'd want to maintain this action further for extremely minimal savings.
