### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by kwsorensen** [fregante/release-with-changelog#56]
"Error: Resource not accessible by integration"

Received after adding the following code to my repo - https://github.com/soraro/tmpnotes/pull/30

**Comment by fregante** [comment]
You're limiting the permissions of the native `secrets.GITHUB_TOKEN`:

https://github.com/soraro/tmpnotes/blob/85ee111efbd3d71879b062cc5962305b109637d2/.github/workflows/ghcr-release.yml#L15-L17

**Comment by kwsorensen** [comment]
What's the recommended way to Permission this step? Using a personal PAT doesn't seem secure. Is there another way you recommend @fregante?

**Comment by fregante** [comment]
The tool needs to create a release, so "contents: write", so it should be dropped since that's the default
