### ISSUE TITLE
Missing option for contributors list

### ISSUE THREAD

**Issue by mdirshaddev** [fregante/release-with-changelog#60]
Hi, Thanks for building this awesome action. I am a newbie in github actions and it workflows. Can you tell how to add contributors in the release list.

**Comment by fregante** [comment]
Thank you for your interest, this will be introduced by using the native generator:

- https://github.com/fregante/release-with-changelog/issues/53


You can keep track of that issue

**Comment by mdirshaddev** [comment]
When i created manually i can see me as a contributors.
![image](https://user-images.githubusercontent.com/68414911/181877539-0c96f0ff-28bb-4425-a466-376e638621db.png)

Workflow triggered i.e., created by action.
![image](https://user-images.githubusercontent.com/68414911/181877560-64721fb5-a720-4860-9c46-a023b1e30549.png)

**Comment by BelKed** [comment]
People are listed as contributors if you mention them in the release description like this: @mdirshaddev

**Comment by mdirshaddev** [comment]
> People are listed as contributors if you mention them in the release description like this: @mdirshaddev

For this I had to add there manually in actions right? @BelKed

**Comment by BelKed** [comment]
I have a [fork](https://github.com/BelKed/release-with-changelog/tree/author-placeholder), where I added a support for author placeholder and I also opened a pull request for this feature (#44), however it wasn’t merged.

**Comment by mdirshaddev** [comment]
@BelKed Ok bro will try yours one. Then ping you back
